export enum ShopTypes {
  CASA_JV = 'CASA JV',
  CASA_OWN = 'CASA OWN',
  FORTUNA_JV = 'FTN JV',
  FORTUNA_OWN = 'FTN OWN',
  FORTUNA_JV2 = 'FTN JV2',
  FORTUNA_SSBT = 'FTN SSBT',
  CASA_SSBT = 'CASA SSBT',
}
